### PR TITLE
Check all table rows upon theme import, not only the first one

### PR DESCRIPTION
**Pull request by ausi**
Currently the `Theme::compareThemeFiles()` method only checks the column names of the first row.

### CODE REVIEW

**Comment by leofeyer** [comment]
Why is this a problem? Shouldn't all rows of a table have the same field names?

**Comment by ausi** [comment]
Because extensions can change the XML file in the `exportTheme` hook this may not always be consistent. I stumbled upon this issue because I removed all unnecessary fields (with e.g. empty or `NULL` values) from the XML-File to reduce the file size.

**Comment by leofeyer** [comment]
So this is actually a fix for a problem that you have created yourself in your extension :laughing:

**Comment by ausi** [comment]
I would say I “discovered” this bug with my extension ;)

**Comment by leofeyer** [comment]
LOL

**Pull request merged**
