### PR TITLE
Feature prepare form data fields

### PR DESCRIPTION
**Pull request by dmolineus**
This pull requests passes the form fields to the `prepareFormData` hook. 

It's for example useful to provide the labels of a select fields as pregenerated values for using them in the form emails. Passing the form fields allows to automatically add them to the `$arrSubmitted` array.

### CODE REVIEW

**Comment by Toflar** [comment]
:+1: but can you please squash the commits? :)

**Comment by dmolineus** [comment]
Done, created new PR at #7693.

**Comment by Toflar** [comment]
You can force push to the same branch so you don't need to close the PR - just to let you know for the next time :)

**Comment by dmolineus** [comment]
Thanks for the hint. :)

**Pull request closed without merging**
