### PR TITLE
Delete old search entry if new URL is more canonical

### LINKED ISSUE #8498: Duplicate entry for key 'url' INSERT INTO tl_search
Ähnlich dem #8460 .
Contao 3.5.17 hat zwei Seitenbäume, für Sprache de und en bei gleicher Domain.
Die Sprachkürzel in der URL sind nicht aktiviert! 
Home Alias bei "de" ist "index", bei "en" ist "home".

Ruft man nun mittels de und en Browser die Home Seiten ohne Alias auf, wird zweimal versucht die Url http://domain.xy/ einzutragen.

### PR DESCRIPTION
**Pull request by ausi**
Fixes #8498, #8460

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Review by aschempp — COMMENTED** [review]
Instead of deleting and adding a new record, how about updating the URL so the existing entry is re-used?

**Comment by ausi** [comment]
> Instead of deleting and adding a new record, how about updating the URL so the existing entry is re-used?

A new record is not always created, this depends on the `if ($objIndex->numRows)` on line 208. So I think deleting the record should be OK, otherwise the logic gets more complicated.

**Comment by leofeyer** [comment]
That's not entirely true. We could run:

```php
$db
    ->prepare('UPDATE tl_search SET url=? WHERE ID=?')
    ->execute($arrSet['url'], $objIndex->id)
;
```

Then the query in line 201 would find the existing record.

**Review by leofeyer — CHANGES_REQUESTED** [review]
If we really want to delete the existing record, we must also remove the child records from `tl_search_index`.

**Comment by ausi** [comment]
> That's not entirely true. We could run:
> 
> ```php
> $db
>     ->prepare('UPDATE tl_search SET url=? WHERE id=?')
>     ->execute($arrSet['url'], $objIndex->id)
> ;
> ```
> 
> Then the query in line 201 would find the existing record.

I don’t think so. This would result in a `Query error: Duplicate entry '...' for key 'url' (UPDATE tl_search...` error. See the reproducing steps from https://github.com/contao/core/issues/8498#issuecomment-280591644

**Comment by ausi** [comment]
> If we really want to delete the existing record, we must also remove the child records from `tl_search_index`.

Addressed in fb408700098cc185b9e14c5ef91311d45bf4df3a

**Comment by leofeyer** [comment]
> I don’t think so. This would result in a `Query error: Duplicate entry '...' for key 'url' (UPDATE tl_search...` error.

You are right, of course.

**Review by leofeyer — APPROVED** [review]

**Comment by aschempp** [comment]
Why would that result in a duplicate index issue when we update the URL?

**Comment by ausi** [comment]
Because an entry with the new URL might already exist and the URL column has an unique index. I tried it out and got the `Duplicate entry '...' for key 'url'` error...

**Comment by aschempp** [comment]
I don't understand that.
 1. we are searching for a database record by checksum
 2. if that record exists, we must delete it and not modify the URL, because the URL could exist
 3. then we create a record with that URL?

**Comment by fritzmg** [comment]
@aschempp see https://github.com/codefog/contao-cookiebar/issues/21#issuecomment-263834643 for an example. The same page could be present multiple times in the `tl_search` table, with different GET parameters and different checksums. If you try to update the URL for one particular checksum, you might have duplicate URLs.

**Comment by aschempp** [comment]
I do understand that, but how can this be an issue if we add a new database record with exactly that URL and checksum just a few code lines later?

**Comment by ausi** [comment]
> I do understand that, but how can this be an issue if we add a new database record with exactly that URL and checksum just a few code lines later?

A few lines later there is a check if an entry with that URL already exists. Only if it doesn’t exist a new record is created, otherwise the existing record gets updated. And this record doesn’t have the same URL as the record we have deleted.

**Pull request merged**
