### PR TITLE
Eigene Attribute mit an das Template weitergeben

### PR DESCRIPTION
**Pull request by katgirl**
Damit man eigene Werte z.B. aus dem Isotope AttributeWizzard an das Template durchreichen kann.

### CODE REVIEW

**Comment by aschempp** [comment]
If we add that (and I'm not sure we should), I would prefer something like this:

```php
$arrOptions[] = array_replace(
    $arrOption,
    array(
        'type'       => 'option',
        'name'       => $this->strName . ((count($this->arrOptions) > 1) ? '[]' : ''),
        'id'         => $this->strId . '_' . $i,
        'checked'    => $this->isChecked($arrOption),
        'attributes' => $this->getAttributes(),
    )
);
```

**Comment by discordier** [comment]
I second the remark by @aschempp, a new sub array feels wrong here.

**Comment by Toflar** [comment]
Same here, I'm with @aschempp and @discordier. However, I do see the need for additional data for the options, so I agree we should do something about this here.

**Comment by katgirl** [comment]
change

**Comment by discordier** [comment]
No it seems like the indention is one step too far, isn't it?

**Comment by aschempp** [comment]
I guess @discordier means the coding style, I had to read it several times before understanding :D

Shouldn't we add the same to the group option?

**Comment by discordier** [comment]
Of course I mean the coding style. Otherwise indention does not make sense. ;)

**Comment by leofeyer** [comment]
@contao/developers Do you want me to merge this (with the CS fixed)?

**Comment by aschempp** [comment]
Well I feel it could be handy in some rare cases, and does not harm for the standard behavior.

**Comment by Toflar** [comment]
I'm 👍  on merging this, yes. Also allows e.g. to add images per option etc. A very valid use case.

**Comment by discordier** [comment]
Also a :+1: from me on this one. Very valid use case.

**Comment by leofeyer** [comment]
Implemented in contao/core-bundle@80dd9c97e892bef55c73caea1de420ac8a0cb8b7.

**Pull request closed without merging**
