### PR TITLE
Set default to NULL on copy if nullIfEmpty is set

### PR DESCRIPTION
**Pull request by aschempp**
I have a date field in my DCA which can be NULL and `doNotCopy` enabled. If the record is duplicated, the value currently results in 01.01.1970.

### CODE REVIEW

**Comment by leofeyer** [comment]
Shouldn't we use `Widget::getEmptyValue()` here?

**Comment by aschempp** [comment]
I thought about that too, but that means an integer field would get '0' as default, which is probably not what you want?

**Comment by leofeyer** [comment]
0 seems correct for an INT field IMHO.

**Comment by aschempp** [comment]
But its very likely not what you want in a field, because you want to enter a new value.

What happens if a new record is created? Are we using 0 or empty?

**Comment by leofeyer** [comment]
We are using `Widget::getEmptyValue()` 😄

**Comment by leofeyer** [comment]
Fixed in aff8643c9651ac6061c8e0c414712d10b4d76dfa.

**Pull request closed without merging**
