### PR TITLE
add hook to alter comment form fields

### PR DESCRIPTION
**Pull request by backbone87**
ref https://github.com/contao/core-bundle/issues/1512

### CODE REVIEW

**Review by Toflar — APPROVED** [review]
CS changes need to be applied but otherwise this looks fine.

**Comment by leofeyer** [comment]
Contao 3 is in the "security fixes only" phase of the long term support phases and since this is not a security fix, I am closing the ticket.

**Comment by backbone87** [comment]
@leofeyer can you please read the related discussion in https://github.com/contao/core-bundle/issues/1512
without this hook its nearly impossible to make contao 3.5 comments to adhere to the DSGVO

**Comment by fritzmg** [comment]
@backbone87 since Contao 3.5 won't get any updates anymore we might as well just instruct people to manually patch the `Comments.php` - since there is no danger that those changes would get lost. The patch could be distributed via the `contao-privacy` extension.

**Pull request closed without merging**
