### PR TITLE
Update FrontendTemplate.php

### PR DESCRIPTION
**Pull request by MoniqueHahnefeld**
#8348

### CODE REVIEW

**Comment by leofeyer** [comment]
This does not make much sense to me. What's the initial problem?

**Comment by MoniqueHahnefeld** [comment]
The initial problem is that my registered parameter are in the url and not "unused" and this function throw an error. so I can not process the follow kind of url: xxxx/de/produkte/adapter/adapterfinder/camera/nnn/objectiv/xxx.html
May the problem is in this method:
\Input::hasUnusedGet() 
??
get-parameter to declare as unsed instead of they are used is not really good or ?

**Comment by aschempp** [comment]
I agree with @leofeyer. Why are the parameters in `TL_AUTO_ITEM` if they are in your url?

**Comment by MoniqueHahnefeld** [comment]
ok yes I thought I have to prepare the get-parameter within the $arrFragments into the getPageIdFromUrl() . Now I got it work. It was a little bit tricky to get no conflicts with other extension like events, news and so on. But it's just little bit difficult at all I suppose. Thx @leofeyer @aschempp :)

**Pull request closed without merging**
