### PR TITLE
Reset all filters button

### PR DESCRIPTION
**Pull request by Toflar**
My ticket https://github.com/contao/core/issues/1979 is floating around for quite some time now and everytime I have to reset all filters I think about this again, so here's my pull request to speed up this feature ;)

I've added a @todo because I seriously couldn't find out in what circumstances Contao displays a filter panel at the bottom of a page :D

### CODE REVIEW

**Comment by Aybee** [comment]
Ich benutze in meinem BE etwas Javascript zum Resetten. Vielleicht sind ein paar Stellen davon ja hilfreich. (Ganz unten ist noch ne Option, damit ein ausgewählter Filter sofort greift ohne auf den Submit-Button zu klicken - fand ich immer sehr hilfreich.)
```javascript
(function($) {
  window.addEvent('domready', function() {

    // Create a reset button to reset the panel selects and submit
    // TODO: Create ticket for marking default options with class="default" or data-default="true"
    var submitPanel = $$('.tl_submit_panel') || false;

    if(submitPanel[0]){
      var
        resetButton,
        resetSelects = $$('.tl_filter select, .tl_limit select'),
        searchText = $$('input[type=search]')
      ;

      // create the reset button
      resetButton = new Element('div.reset_button', {
        title: 'Filter, Suche und Limit zurücksetzen - dann neu laden',
        text: 'reset',
        styles: {
          backgroundColor: 'orange',
          borderRadius: '5px',
          cursor: 'pointer',
          display: 'inline-block',
          width: 42,
          height: 22,
          lineHeight: 20,
          textAlign: 'center'
        }
      });

      resetButton.addEvent('click', function() {
        Array.each(resetSelects, function(el) {
          el.getSelected().setProperty('selected', '');
        });
        searchText.erase('value');
        submitPanel[0].getParent('form').submit();
      });

      resetButton.inject(submitPanel[0]);
    }



    // Immediatly reload page after filter select or sort select
    $$('.tl_filter select, .tl_sorting select').addEvent('change', function() {
      this.form.submit();
    });

  });
})(document.id);
```

**Comment by Toflar** [comment]
I still think this is a very good feature and should be moved to core-bundle for 4.2. However, as I did my proposal I cannot really work on this more than I did here. @contao/developers

**Comment by bezin** [comment]
I just had the exact same demand for a filter reset button as proposed here. I would really appreciate this feature :)

**Comment by leofeyer** [comment]
Implemented in contao/core-bundle@bbd17d3981b0efb9ec32ab67a8848e7b9e0f2576. The icon will be exchanged when we merge the back end icons PR.

**Pull request closed without merging**
