### PR TITLE
Issue #7422 no.7

### PR DESCRIPTION
**Pull request by alarstyle**
#7422 no.7

> When debug mode is on, in the backend there is inline style
> margin-bottom: 60px; for <body> tag. And it is changing when user
> toggles debug bar. It can be done with css, just need to add/remove css
> class in <body> tag. This can be useful, for example, if user wants to
> change look of debug bar or make it higher.

### CODE REVIEW

**Comment by aschempp** [comment]
Is this a bug fix? I'm just asking because the debug bar has been removed in Contao 4 and 3.5 is already feature-complete.

**Comment by alarstyle** [comment]
It's not realy a bug fix, it's more like feature that adds more flexibility.
I don't know about Contao 4, but as I can see, in 3.5 debug bar works the same as in 3.4.

**Comment by aschempp** [comment]
The PR is :+1: from me. Dunno if it can still make it into 3.5 though because of the release state.

Ping @leofeyer

**Comment by leofeyer** [comment]
> Dunno if it can still make it into 3.5 though because of the release state.

It cannot. Contao 3.5 is feature complete (RC1), so the ticket would have to be assigned to the next feature release. However, the next feature release is Contao 4.1 and we are no longer using the debug bar in Contao 4 :(

**Comment by alarstyle** [comment]
It's a pity. In any case I was doing this pull request for too long, sorry for that.

**Comment by alarstyle** [comment]
It's a pity. In any case I was doing this pull request for too long, sorry for that.

**Comment by leofeyer** [comment]
I'm sorry it developed that way :(

**Comment by leofeyer** [comment]
I just noticed that the PR does in fact improve the speed of the debug bar, because it no longer requires to change styles via JavaScript (like `$$('#contao-debug>*').setStyle('width',window.getSize().x);`). So we could see this as a bug fix I guess …

**Comment by leofeyer** [comment]
Merged in 782a18b28b606e305bc8ef5b53f1cf2c65966c57.

**Pull request closed without merging**
