### PR TITLE
[RFC] Important part overlay (see #7507 and #7791)

### PR DESCRIPTION
**Pull request by leofeyer**
This is the follow-up PR for #7791, because the ticket was closed somehow.
- [ ] Should we use a different (or bigger) icon?
- [ ] Do we need the functionality in the file picker, too?
- [ ] Cross-browser testing required.

@xchs @ausi Can you please review and help getting the remaining things done?

### CODE REVIEW

**Comment by leofeyer** [comment]
@ausi I have fixed the things you have mentioned.

**Comment by leofeyer** [comment]
@xchs @Zeromax Can you please test again with the changes I have made?

**Comment by xchs** [comment]
Commit 3267b8d39ef1a4d6ab1bb0147afdef27ec019ab7 was not intended for this feature branch, I guess?

I just run my cross-browser tests again and it works flawlessly anywhere (desktop and mobile).

**Comment by leofeyer** [comment]
No it was not. I have updated the branch.

**Comment by leofeyer** [comment]
@contao/developers Please vote in this PR.

**Comment by Toflar** [comment]
:+1:

**Comment by ausi** [comment]
:+1:

**Comment by leofeyer** [comment]
What about the icon overlay? It's pretty small IMHO.

**Pull request closed without merging**
