### PR TITLE
implemented contao/core#8228

### PR DESCRIPTION
**Pull request by fritzmg**

### CODE REVIEW

**Comment by aschempp** [comment]
why not simply use the current page if `rootPage` is not set?

**Comment by asaage** [comment]
if rootPage is not set it will take the current website-Root i rely on that in most installations.

**Comment by fritzmg** [comment]
> why not simply use the current page if rootPage is not set?

Sure, but this way it's more clear to the user what will happen, I think. I am fine with it either way ;). Also this way it can be integrated in Contao 4.2 without potentially breaking the backwards compatibility - some users might have `defineRoot` set (by accident maybe), but not `rootPage`.

**Comment by fritzmg** [comment]
Ah, this is actually invalid, it does not implement what was requested in the original issue. In the orginal issue, the user wants the __parent__ page of the active page (`$objPage->pid`) to be the root of the navigation - however, I implemented it with just the active page (`$objPage->id`).

**Pull request closed without merging**
