### PR TITLE
Issue #7422 no.6

### PR DESCRIPTION
**Pull request by alarstyle**
#7422 no. 6

> Output website title from settings page in the header of backend.

### CODE REVIEW

**Comment by aschempp** [comment]
Can you maybe add a quick screenshot what the end result will look like?

**Comment by alarstyle** [comment]
screenshot

**Comment by Aybee** [comment]
:+1:

**Comment by aschempp** [comment]
:+1:

**Comment by leofeyer** [comment]
I have implemented a similar but responsive solution in contao/core-bundle@f39788662a82c32e826f922467e2713bf1bdc770.

**Pull request closed without merging**
