### PR TITLE
[RTM] Fixed Controller::getForm()

### PR DESCRIPTION
**Pull request by Toflar**
which was relying on the Form class and always being rendered as a content element.

see https://github.com/contao/core-bundle/pull/582

### CODE REVIEW

**Comment by aschempp** [comment]
Why not just pass in the FQCN?

**Comment by Toflar** [comment]
Because it does not make sense? You can only render it as CE or MOD. There is no other possibility.

**Comment by aschempp** [comment]
somewhat true, yes. But it would be some sort of *constant* instead of a strange string.

**Comment by Toflar** [comment]
¯\_(ツ)_/¯

**Comment by leofeyer** [comment]
As discussed in Mumble on December 14th, @Toflar will change the argument to `$blnModule` and then the PR can be merged.

**Comment by Toflar** [comment]
Updated.

**Comment by aschempp** [comment]
Personally I prefer true flags to enable a new feature instead of this, but obviously both works.

**Comment by leofeyer** [comment]
Merged in contao/core-bundle@078cb3438f212b6f5a5d722ea7707851e2110bc7.

**Pull request closed without merging**
