### PR TITLE
Fix markup minification

### PR DESCRIPTION
**Pull request by ausi**
See #7734

### CODE REVIEW

**Comment by leofeyer** [comment]
Can you elaborate on your changes?

**Comment by ausi** [comment]
I added a comment in https://github.com/contao/core/issues/7734#issuecomment-122367057 just now.

**Comment by leofeyer** [comment]
In your implementation, you are preserving the chunk if it does not have a known JavaScript type. This implies that there is no optimization at all:

```html
<div id="my-slider">
    <img src="image1.jpg">
    <script type="text/html">
        <img src="image2.jpg">
    </script>
</div>
```

However, the chunk could be optimized:

```html
<div id="my-slider">
<img src="image1.jpg">
<script type="text/html">
<img src="image2.jpg">
</script>
</div>
```

Is there a reason why we should **not** optimize the markup this way?

**Comment by ausi** [comment]
We should only optimize known types, `text/html` might be a special case which we could also optimize, but types like `text/plain` or `text/markdown` must not be optimized. E.g. changing

```html
<script type="text/markdown">
# Headline

    Code block starting with 4 spaces
</script>
```

to

```html
<script type="text/markdown">
# Headline
Code block starting with 4 spaces
</script>
```

would be bad.

Should I update the pull request to include the `text/html` case?

**Comment by leofeyer** [comment]
No, I have already merged it locally.

**Comment by leofeyer** [comment]
Merged in c4e4e6f098922d6a98a489b96d5cdb591550f934. I have removed the CSS check, because currently there is no other type than `text/css`.

**Pull request merged**
