### PR TITLE
ce_content :: added save callback to youtube field to extract video id from a url

### PR DESCRIPTION
**Pull request by uvoelkel**
Quite a few users struggle with extraction of the video id from a youtube url. Especially with the recently added forced playlist.
This patch adds a save callback to the ce_content.youtube field that extracts the video id from a complete url. The user can just copy and paste whatever the address bar says.

### CODE REVIEW

**Comment by leofeyer** [comment]
Will this PR ever be completed or can I close the ticket?

**Comment by u-voelkel** [comment]
Sorry, I completely forgot about this one :(
Any other format I am missing?

**Comment by fritzmg** [comment]
I usually use this regex: http://stackoverflow.com/questions/2936467/parse-youtube-video-id-using-preg-match/6382259#6382259

**Comment by leofeyer** [comment]
Implemented in contao/core-bundle@afeef802c5cee9982c0de7b80b2f3bc2053c22a2. The YouTube element now also uses its own template and is embedded via iframe by default.

**Pull request closed without merging**
