### PR TITLE
Feature: "previous"

### PR DESCRIPTION
**Pull request by marcobiedermann**
I suggest renaming all "prev" links to "previous" to make it more consistent and easier to develop themes.

### CODE REVIEW

**Comment by fritzmg** [comment]
I think this is already normalized in Contao 4.

**Comment by marcobiedermann** [comment]
@fritzmg Yes, I know. But it would be great if this would land in Contao 3.x

**Comment by fritzmg** [comment]
That's not possible, because that would break backwards compatibility. If this was integrated and someone updates their Contao installation, their "previous" buttons might not be styled anymore all of a sudden.

**Comment by marcobiedermann** [comment]
@fritzmg Sure. But you could release Contao 3.6 and let people know

**Comment by aschempp** [comment]
There will not be a new Contao 3.x version (see [release plan](https://contao.org/en/release-plan.html))

**Comment by fritzmg** [comment]
> @fritzmg Sure. But you could release Contao 3.6 and let people know

Even if there was a Contao 3.6, it cannot be integrated into Contao 3.6. Minor versions cannot break the backwards compatibility. Things like that can only be changed in major versions.

**Pull request closed without merging**
