### PR TITLE
Add contributing guidelines

### PR DESCRIPTION
**Pull request by ausi**
As already mentioned in #6904, it would be great to have some guidelines for contributing to Contao on GitHub. On every new pull request I’ve forgotten which one is the right branch. Also see https://github.com/contao/core/pull/7567#issuecomment-71015098 or https://github.com/contao/core/pull/7559#issuecomment-69489788

Inspired by [atom’s CONTRIBUTING.md](https://github.com/atom/atom/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xchs** [comment]
+1 of course 

In the "Submitting Issues" section I would further add something like

* clearly describe the issue including all the steps that you follow in order to reproduce the bug in the Contao online demo

since this is something Leo has to ask over and over again. :)

**Comment by ausi** [comment]
@xchs added.

**Comment by aschempp** [comment]
+1

**Comment by leofeyer** [comment]
Merged (with changes) in 9594dd8e11c6a71806335bdca7ffbb15619d014a.

**Pull request closed without merging**
