### PR TITLE
Changing to work without the div

### PR DESCRIPTION
**Pull request by MacKP**
See Ticket: https://github.com/contao/core/issues/8396

### CODE REVIEW

**Comment by leofeyer** [comment]
I think we are going to have a problem if we do not also adjust [line 11](https://github.com/contao/core/blob/master/system/modules/core/templates/mootools/moo_accordion.html5#L11), which expects the markup to contain DIVs.

@aschempp /cc

**Comment by aschempp** [comment]
no idea what that actually does… do you?

**Comment by leofeyer** [comment]
It selects the DIV after the toggler and fades it in. Maybe `getNext('.accordion')` works?

**Comment by leofeyer** [comment]
> Maybe `getNext('.accordion')` works?

It does actually. 😄

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@f74d7789885d97cea5d382516c34fc73f10f18bc.

**Pull request closed without merging**
