### PR TITLE
[RTM] Hotfix/autofocus

### PR DESCRIPTION
**Pull request by Toflar**
See #8419.

Screencast GIF (very slow for some reason but I'm too lazy to investigate):
example

### CODE REVIEW

**Comment by leofeyer** [comment]
What if the first focusable field is a TinyMCE textarea?

**Comment by Toflar** [comment]
> What if the first focusable field is a TinyMCE textarea?

Implemented support in eba721d79b79e8d3dd690bea5a8eb24ca89f5631. Pretty cool, hm? 😎

**Comment by leofeyer** [comment]
Does this work if `TinyMCE.init()` is called before `Backend.autoFocusFirstInputField()`?

**Comment by Toflar** [comment]
Why should this ever happen?

**Comment by discordier** [comment]
I have an issue with this.
This will prevent me from scrolling though the page with the keyboard arrow keys without prior clicking outside of the autofocus input field or tabbing to the first non input element.
As soon as the cursor is within the field, the browser auto completion will get triggered by the arrow keys  instead of page scrolling.
Maybe a non issue for Mac Users as these are used to scrolling with the pad but definately an issue on other platforms where people use the keyboard where possible.

**Comment by Toflar** [comment]
How is this related to this at all? We have had autofocus ever since so you had that issue ever since too?

**Comment by discordier** [comment]
I do not know about you but in my (stock) 3.5.15, the search field is not autofocussed and hence I can happily scroll up and down through the list views. I wonder why this should be different for me than for you.

In your screen cast, the search field is autofocus'ed and therefore this will not be possible anymore.

**Comment by fritzmg** [comment]
The autofocus attribute doesn't seem to work in all browsers, maybe that's why you didn't have an issue yet.

**Comment by Toflar** [comment]
You weren't talking about the list view. You were talking about scrolling in general.
I see. I actually like the feature but I can understand your concerns. The question is whether we want to skip the filter panel or restrict the focussing to the edit views only (which will cause e.g. the maintenance mode screen not to focus anything at all by default).

**Comment by discordier** [comment]
Maybe you misunderstood what I am referring to.
You mean the auto focus in the EDIT view, that is present and will still be present.
This is not that much of an issue to me as when editing one will most likely want to use the input fields.
I am only talking about the LIST view, where this does not bring any benefit to me but imposes above explained issue.
Scrolling through the article or page list is not possible anymore.

**Comment by discordier** [comment]
Skipping the panels would be very good IMO.

Concerning the maintenance mode... this will then select the "live update ID" input always which is the only input on that screen that will get modified only when performing an upgrade and therefore does not make any sense to have it always auto focus'ed.

**Comment by Toflar** [comment]
This was obviously just a general example...you can take anything you like. The question is whether to skip explicitly the filter panel or limit the focussing feature to the known edit masks (edit, editAll etc.) only.

**Comment by discordier** [comment]
I would limit it to the edit masks.

**Comment by aschempp** [comment]
I would only apply it to the edit mask too.

**Comment by leofeyer** [comment]
Me too.

**Comment by Toflar** [comment]
Removed other autofocus related stuff in bd8d338c070cac131fbcb3b47720da699c311d6d (this was very likely interfering with the autofocus attribute before, so I don't know how this could have ever worked properly at all) and implemented the restriction on all edit masks only in c407b53fccf560d9fcde7da0793a6b12681c307c.

**Comment by leofeyer** [comment]
Again, what happens if `TinyMCE.init()` is called before `Backend.autoFocusFirstInputField()`?

**Comment by Toflar** [comment]
> Again, what happens if TinyMCE.init() is called before Backend.autoFocusFirstInputField()?

Again: Why should this ever happen?

**Comment by leofeyer** [comment]
E.g. if someone moves the scripts down to the end of the page (people are using hooks to accomplish this) or someone adds the `async` attribute.

**Comment by aschempp** [comment]
> E.g. if someone moves the scripts down to the end of the page (people are using hooks to accomplish this) or someone adds the async attribute.

In the backend? 😧

**Comment by Toflar** [comment]
I don't see what you want to tell me tho be honest. The `Backend.autoFocusFirstInputField()` is triggered on `domready` just like all the other stuff like `Backend.makeWizardsSortable()` and  	`Backend.enableToggleSelect()`. If the DOM is ready, the `<textarea>` is gonig to get the focus. That's it. If then `tinyMCE.init()` is executed, it notices the focus on the target element and focuses itself. Your example would require to execute `tinyMCE.init()` before the DOM is ready which seems strange to me.
But I can add the feature so it works in both cases, if you feel better with it :)

**Comment by leofeyer** [comment]
> is triggered on domready just like all the other stuff

You are right, I did not think of this. Then the PR is `RTM` to me.

**Comment by leofeyer** [comment]
Merged in d34662322e4f5d226990279472a7960b88601b87.

**Pull request closed without merging**
