### PR TITLE
Allow IP ranges in trusted proxies

### PR DESCRIPTION
**Pull request by aschempp**
The `$GLOBALS['TL_CONFIG']['proxyServerIps']` allows for a list of trusted proxy IPs. In my case, I had to whiteliste several subnetworks of proxy servers, so the simple list was only partially useful.

This PR adds support for IPv4 subnetworks in the list of trusted proxies.
Example: `192.168.1.0/24` would white-list IPs ranging from `192.168.1.1` to `192.168.1.254`.

### CODE REVIEW

**Comment by qzminski** [comment]
+1

**Comment by Toflar** [comment]
We could use a library for that. E.g. https://github.com/Jalle19/php-whitelist-check (100% code coverage) :)

**Comment by discordier** [comment]
We should also allow ipv6

**Comment by leofeyer** [comment]
Where is your code from? Did you use the Symfony routines?

http://symfony.com/doc/current/reference/configuration/framework.html#trusted-proxies

**Comment by aschempp** [comment]
No, I used some code from StackOverflow. I agree we could use the component but then we should only add it in Contao 4. That would also mean we would be compatible with the Symfony container definition.

**Comment by leofeyer** [comment]
The setting has been removed in Contao 4, because Symfony now takes care of it.

**Pull request closed without merging**
