### PR TITLE
provide all data from rss in the template

### PR DESCRIPTION
**Pull request by frontendschlampe**
actually you provide only some special information of the rss-feed to the template - with this PR you will provide every information to template

### CODE REVIEW

**Comment by Toflar** [comment]
+1

**Comment by discordier** [comment]
:+1:

**Comment by backbone87** [comment]
+1

**Comment by qzminski** [comment]
+1

**Comment by leofeyer** [comment]
Merged in 4c714e9e9cf5b11c5b6fcb707b63f935f8ce332a.

**Pull request closed without merging**
