### PR TITLE
improve description for using lightbox attribute in link element

### PR DESCRIPTION
**Pull request by frontendschlampe**
I was searching for nearly half an hour to get the correct wording and that's why I think this will be a better description for using this feature.

### CODE REVIEW

**Comment by leofeyer** [comment]
Does the issue still occur in Contao 3.5? If yes, please rebase the PR, if no, please close it.

**Comment by leofeyer** [comment]
@frontendschlampe If the PR is still relevant, it needs to be rebased. Otherwise please close it.

**Comment by frontendschlampe** [comment]
I have to check again. But my initial PR just changes the wording of description. Than @Aybee added support for width and height option. Should I add it to my PR?

**Comment by Aybee** [comment]
Wenn der neue Hilfetext erklärt, wie man über das Attribut die Höhe und Breite einstellen kann und wie man Ligthbox-Links als zusammenhängend oder Singles definiert (Album), dann würde sich anbieten, j_colorbox dementsprechend an moo_mediabox anzugleichen, sonst müsste man im Text ja eine Unterscheidung zwischen colorbox und mediabox machen.

**Comment by frontendschlampe** [comment]
dafür muss ich dann natürlich das JS noch mit anpassen

**Comment by frontendschlampe** [comment]
@leofeyer Was sagst du?

**Comment by Aybee** [comment]
> dafür muss ich dann natürlich das JS noch mit anpassen

Ja, so in etwa, wie ich das oben schon vorbereitet hatte.

**Comment by leofeyer** [comment]
> @leofeyer Was sagst du?

Da der PR so unübersichtlich ist, weiß ich leider nicht, was Du eigentlich ändern wolltest.

**Comment by frontendschlampe** [comment]
ursprünglich habe ich nur eine Zeile in der system/modules/core/languages/en/tl_content.xlf angepasst ;-)

**Comment by leofeyer** [comment]
Und was genau hattest Du da angepasst?

**Comment by frontendschlampe** [comment]
ALT:
`<trans-unit id="tl_content.rel.1">
<source>To trigger the lightbox, enter a &lt;em&gt;rel&lt;/em&gt; attribute here.</source>
</trans-unit>`

NEU:
`<trans-unit id="tl_content.rel.1">
<source>To trigger the lightbox (e.g. mediabox, slimbox, colorbox), enter a &lt;em&gt;rel&lt;/em&gt; attribute here. It will be replaced automatically with &lt;em&gt;data-lightbox&lt;/em&gt; if output format html is selected. Please use the following format: &lt;em&gt;lightbox[name-of-lightbox width height]&lt;/em&gt;</source>
</trans-unit>`

ich kann das auch gern nochmal rebasen

**Comment by fritzmg** [comment]
The description only fits if you use `moo_mediabox`.

**Comment by frontendschlampe** [comment]
> The description only fits if you use `moo_mediabox`.

But I think it will also work with colorbox, because rel=lightbox will be replaced?!

**Comment by fritzmg** [comment]
No I mean the settings. They only affect the MediaBox.

**Comment by frontendschlampe** [comment]
> No I mean the settings. They only affect the MediaBox.

No ... I don't think so! It's also for mediabox.

**Comment by fritzmg** [comment]
You mean Colorbox? No, those settings will not affect the Colorbox ;)

**Comment by leofeyer** [comment]
I don't see an advantage in a (much too) long explanation. On the one hand, people will not read it, and on the other hand, people cannot copy and paste the example code from the tooltip. Also, `(e.g. mediabox, slimbox, colorbox)` seems pretty confusing to me.

Then there is also the problem mentioned by @fritzmg. And I don't want to have to implement the feature into every lightbox script we are adding to the core.

**Comment by frontendschlampe** [comment]
> You mean Colorbox? No, those settings will not affect the Colorbox ;)

But I'm sure, that I have test it, that it works for colorbox. Long time ago ... I have to check again.

**Comment by frontendschlampe** [comment]
As I said ... it's to long time ago I made this PR ... that's why I will close and make a new one if necessary .

**Comment by fritzmg** [comment]
@frontendschlampe just look at the templates. Only `moo_mediabox` uses those settings.

**Comment by Aybee** [comment]
> @fritzmg  The description only fits if you use moo_mediabox. 

That's why I provided the patch for colorbox in https://github.com/contao/core/pull/7517#issuecomment-66898726 for that it also works with colorbox.

**Comment by fritzmg** [comment]
That code is still missing the usage of `iframe`, `inline` and `ajax` though.

**Pull request closed without merging**
