### PR TITLE
Make BackendUser::authenticate() return true to honor documentation.

### PR DESCRIPTION
**Pull request by discordier**
Before the method was returning null which is in contrast to the implementation in User and FrontendUser classes.

### CODE REVIEW

**Comment by leofeyer** [comment]
This change is actually wrong, because the method would return `true` even if the user could **not** be authenticated (but `TL_SCRIPT == 'contao/index.php' is true). Also, the return value is never used.

**Comment by aschempp** [comment]
Be aware that we already patched this in Contao 4 (see https://github.com/contao/core-bundle/commit/60db487c70a51f3f320e4c2af4f388990fba9aac)

**Comment by leofeyer** [comment]
@aschempp Thanks for the heads up. The patch in Contao 4 is actually correct and should be back ported here.

**Comment by discordier** [comment]
You are right about the url evaluating. Feel free to close and backport from C4.

**Comment by Zeromax** [comment]
isn't this related? #6850

**Comment by discordier** [comment]
Related but with a bigger scope.

**Comment by leofeyer** [comment]
Fixed in dc7116852eee8af9f5cbc6397612578d5c39e74e.

**Pull request closed without merging**
