### PR TITLE
[RTM] Fix breadcrumb broken in file picker when using it within tl_page

### PR DESCRIPTION
**Pull request by Toflar**
When you want to add a filepicker field to tl_page, the breadcrumb in the filepicker popup does not work. This is because tl_page does always add the pages breadcrumb which just redirects if `node` is set in the URL even if it is not meant for the page but the file tree. Not sure if my fix is correct though.

/cc @contao/developers

### CODE REVIEW

**Comment by leofeyer** [comment]
Your fix is ok, but `if ($_GET['do'] == 'page')` seems simpler to me.

**Comment by Toflar** [comment]
Imho it is still fighting the outcome, not the source of the problem. What do you think about renaming `node` to `fileNode` and `pageNode`?

**Comment by leofeyer** [comment]
I'm fine with that as well.

**Comment by Toflar** [comment]
PR updated.

**Comment by leofeyer** [comment]
What about using `pn`, `fn` and `tn` as keys? Would keep the URL shorter.

**Comment by Toflar** [comment]
Updated.

**Comment by leofeyer** [comment]
Merged in 6827dd86c28f03e9d75aa69b7e5525141209fec4.

**Pull request closed without merging**
