### PR TITLE
Updated links to manual

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by leofeyer** [comment]
Hm, URL not found? https://docs.contao.org/manual/current/01-installation/

**Comment by aschempp** [comment]
Fixed

**Comment by leofeyer** [comment]
I'd prefer to link to https://docs.contao.org/books/manual/current/en/01-installation/installing-contao.html instead of the index page. It somehow looks like there was only the one paragraph, don't you think?

**Comment by aschempp** [comment]
Fine with me :-)

**Comment by leofeyer** [comment]
Changed in 7f46a899d570124781fe5f13e19eb87c509279bb.

**Pull request closed without merging**
