### PR TITLE
convertRelativeUrls - don't convert tel: & sms: in href

### PR DESCRIPTION
**Pull request by matzke**
... alternatively we could use a const or else so we are able to put search params in a config

### CODE REVIEW

**Comment by Toflar** [comment]
> . alternatively we could use a const or else so we are able to put search params in a config

I don't think that makes sense. Why should `sms:` ever be converted? :) I think you could extend your list by `skype:` and `sftp`, couldn't you?

**Comment by leofeyer** [comment]
Fixed in ae54893b849db287f81a156d2b63f2706eff7ebf.

**Comment by discordier** [comment]
IMO this is wrong. There are so many schemes more than the ones now implemented.
IMO we should rather convert everything that does not begin with a scheme.
What about:
```php
if (!preg_match('@^([a-z0-9]+:|#)@i', $strUrl))
```

**Comment by Toflar** [comment]
Good idea!

**Comment by leofeyer** [comment]
> There are so many schemes more than the ones now implemented.

For example?

**Comment by discordier** [comment]
http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by leofeyer** [comment]
I meant which other protocols are relevant in a web site context?

**Comment by discordier** [comment]
At a quick glance the following make sense (especially when viewing from an intranet point of view):
- ldap
- chrome
- dns
- jabber
- news
- nntp
- ws and wss (when working in javascript context for websockets - must not be rewritten)
- irc
- irc6
- mumble
- smb
- ssh
- teamspeak
- webcal

**Comment by leofeyer** [comment]
I have implemented your suggestion in bda45bcea4e3160a80bf4cfbb60f88dfe945386e.

**Comment by discordier** [comment]
Thanks a lot :+1:, have you (unit-) tested it?

**Comment by leofeyer** [comment]
I have ~~(unit-)~~ tested it.

**Comment by leofeyer** [comment]
But since it was your suggestion, I assume that you have :)

**Comment by matzke** [comment]
Excellent! Great discussion. Good work. Thank you!

**Comment by leofeyer** [comment]
Unfortunately, there is a related problem to this:

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Idna.php#L127

@discordier How do we know which protocols require `://` and which require only `:`?

**Comment by leofeyer** [comment]
Never mind, I have fixed it myself in 9e7e05d88d98294bd793a3c3ad20a54b86d125ca.

**Pull request closed without merging**
