### PR TITLE
Added @deprecated notice to Config::getActiveModules

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by leofeyer** [comment]
I cannot merge pull requests into the master branch. Please either use `hotfix/*` or `develop`.

**Comment by aschempp** [comment]
Would you want a new PR? Or just cherry-pick the changes?
I remember we should not PR on a hotfix branch, because all PRs are closed when the branch is released (and branch got deleted without PR merged)… ?

**Comment by leofeyer** [comment]
Forget it. @discordier has showed me the light ;)

**Comment by leofeyer** [comment]
Merged in f6bc52f5eca8c4180dcd5ba4e97271edb8afc991.

**Pull request closed without merging**
