### PR TITLE
parseArticles hook as in ModuleNews

### PR DESCRIPTION
**Pull request by wtom**

### CODE REVIEW

**Comment by leofeyer** [comment]
What do you need the hook for?

**Comment by discordier** [comment]
I guess he wants to add custom data to each news item.
Something like adding support for a linked element or something like that comes into mind.

**Comment by leofeyer** [comment]
@discordier So would you suggest to add the hook?

**Comment by wtom** [comment]
discordier is right. also i think it's pretty good to have the same functionality in the different parts of contao. why having the hook in the news module and not in the article module.

**Comment by discordier** [comment]
@leofeyer In the end it does not harm and I can think of valid reasons to need this hook. However I have not yet really needed it as I was always hacking away via template and the like.
I guess some people might find it handy.
Therefore +1 from me. What do the other @contao/developers think about it?

**Comment by ausi** [comment]
Am I right that this PR suggests to use the same name for the new hook as the already existing parseArticles hook in [system/modules/news/modules/ModuleNews.php:187-195](https://github.com/contao/core/blob/1f7448f356cbef9299d7285b2b3068723e620eb1/system/modules/news/modules/ModuleNews.php#L187-L195)?

I don’t think this would be a good idea.

**Comment by discordier** [comment]
Regarding the name, @ausi is right. We should name it different.

**Comment by leofeyer** [comment]
@wtom Can you please adjust your PR accordingly? I'd suggest to name the hook "parseArticle" (singular).

**Comment by ausi** [comment]
Wouldn’t `moduleArticleCompile`, `articleCompile` or `compileArticle` be a better name for this hook?

**Comment by leofeyer** [comment]
I could live with `compileArticle`, too.

**Comment by leofeyer** [comment]
Implemented in a9e21702c943751deb512e9de47a1687110f03f4.

**Pull request closed without merging**
