### PR TITLE
remove $(document).ready()

### PR DESCRIPTION
**Pull request by marcobiedermann**
All functions are called at the bottom of the page, which means the document is already ready.

### CODE REVIEW

**Comment by leofeyer** [comment]
This may be right, but since we don't know, why not leave the function call there? Does it noticeably affect the performance?

**Comment by marcobiedermann** [comment]
It does not affect the performance that much, just a bit.
I think this is irrelevant and so less code is cleaner code. It will work perfectly fine without the extra function call.

**Comment by marcobiedermann** [comment]
> So to get the best perceived load time, put your script **at the bottom of the page**. […] And if you're going to do that, then there's **no need to use `ready`**, though of course you could if you liked.

http://stackoverflow.com/questions/6026645/document-readyfunction-vs-script-at-the-bottom-of-page

**Comment by leofeyer** [comment]
I know. But can we be sure that the scripts are always at the bottom of the page? What if someone adds a module via insert tag?

**Comment by Aybee** [comment]
What if something is included with `$GLOBALS['TL_BODY'][]`?
I like this domready wrapper as it also is a reminding marker for that the script needs the DOM to be loaded first.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by Toflar** [comment]
We can safely remove them. That's my opinion :)

**Comment by aschempp** [comment]
I would not remove them. Also because they're a safe wrapper for variables and jquery (like so:)

```js
jQuery(document).ready(function($) {
   // all variables wrapped in function and $ is jQuery
});
```

**Comment by aschempp** [comment]
Which means I would remove the outer function ;-)

**Comment by leofeyer** [comment]
But the outer function is shorter, so in terms of page size optimization, it would make more sense to remove the inner one :)

**Comment by ausi** [comment]
IMO we should still listen to *domready*, because someone could rely on the current behaviour. But there is a shorter version:

Before:

```js
(function($) {
	$(document).ready(function() {
		// code…
	});
})(jQuery);
```

After:

```js
jQuery(function($) {
	// code…
});
```

**Comment by backbone87** [comment]
i think ausi's variant is the way to go. keeps the global clean and you get a save jQuery reference and are safe, if your script isnt at the end of the body.

**Comment by leofeyer** [comment]
Is there a shorter version for MooTools as well?

```js
// Current wrapper
(function($) {
    window.addEvent('domready', function() {
        // …
    });
})(document.id);
```

**Comment by aschempp** [comment]
Well you don't need the outer wrapper if you simply use document.id instead of $ in your code

**Comment by leofeyer** [comment]
I know. But that is actually not the answer to the question :)

**Comment by backbone87** [comment]
```js
window.addEvent("domready", function() {
  var $ = document.id;
});
```

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@ef20adfb6917918fd3769f0552bd852ed5039083.

**Pull request closed without merging**
