### PR TITLE
Hash the autologin token in the database

### PR DESCRIPTION
**Pull request by leofeyer**
This PR implements #8888.

### CODE REVIEW

**Review by ausi — APPROVED** [review]
👍

**Comment by ausi** [comment]
Do we want to hash other tokens that are stored in the DB too?

**Comment by leofeyer** [comment]
My first impulse was to hash all tokens, however, after re-reading the [stackoverflow post](https://stackoverflow.com/questions/549/the-definitive-guide-to-form-based-website-authentication/477578#477578), I do no longer thinks so. Only "password like" tokens need to be hashed. Also, unused opt-in tokens are purged after 24 hours now (GDPR), so hashing provides no additional value.

**Comment by aschempp** [comment]
Would it be possible to migrate existing autologin tokens instead of completely breaking them?

**Comment by leofeyer** [comment]
It would sure be possible, however, existing tokens are potentially compromised, therefore we should explicitly break them IMHO.

**Pull request merged**
